version: '3.4'

services:
  stackup_docker_db_demo:
    image: ${DOCKER_REGISTRY-}stackupdockerdbdemo
    build:
      context: .
      dockerfile: stackup_docker_db_demo/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - "DatabaseSettings__MongoConnectionString=mongodb://stackupMongo:27017"
      - "DatabaseSettings__PostgressConnectionString=host=stackupPostgres;Port=5432;Database=Stackup;User Id=admin;Password=admin;"
      - "CacheSettings__RedisCache=stackupRedis:6379"
  
  stackupMongo:
    image: mongo
    container_name: stackupMongo
    restart: always
    ports:
      - "27017:27017"

  stackupRedis:
    image: redis:alpine
    container_name: stackupRedis
    restart: always
    ports:
      - "6379:6379"

  stackupPostgres:
    image: postgres
    container_name: stackupPostgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stackup_postgress
    volumes:
      - stackup_postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.17
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8009:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  stackup_postgres_data:
  pgadmin-data: